apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dogecoin-core.fullname" . }}
  labels:
    {{- include "dogecoin-core.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "dogecoin-core.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dogecoin-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dogecoin-core.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 101
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: rpc
              containerPort: 22555
              protocol: TCP
            - name: p2p
              containerPort: 22556
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - dogecoin-cli
                - getinfo
            initialDelaySeconds: 60
            periodSeconds: 120
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - dogecoin-cli
                - getinfo
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /home/dogecoin/.dogecoin
            {{- if .Values.config }}
            - name: config
              mountPath: /home/dogecoin/.dogecoin/dogecoin.conf
              subPath: dogecoin.conf
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.config }}
      volumes:
        - name: config
          configMap:
            name: {{ include "dogecoin-core.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
